// Lista de nichos compartilhada entre servidor (classificação) e cliente (resolvePack).
export const NICHE_IDS = ['infoprodutos', 'clinicas', 'ecommerce', 'servicos', 'agencias', 'app', 'imobiliaria', 'restaurante', 'academia', 'automotivo', 'beleza', 'petshop', 'turismo', 'eventos', 'educacao', 'reforma', 'moda', 'financas', 'seguros', 'saude', 'tecnologia', 'confeitaria', 'limpeza', 'energiasolar', 'agro', 'logistica', 'fotografia', 'generico']

export const NICHE_HINTS = {
  infoprodutos: "mentorias, cursos, infoprodutos, educação online, lançamentos",
  clinicas: "clínicas, odontologia, estética, harmonização, dermatologia, saúde",
  ecommerce: "loja virtual, e-commerce, venda de produtos físicos, D2C",
  servicos: "advocacia, contabilidade, arquitetura, serviços profissionais locais",
  agencias: "agências de marketing, consultorias, prestação B2B",
  app: "aplicativo, app, SaaS, software, ferramenta digital, automação, plataforma, app no WhatsApp, fitness/saúde/produtividade digital",
  imobiliaria: "imobiliária, corretor de imóveis, venda/locação de imóveis, lançamentos imobiliários, construtora, incorporadora",
  restaurante: "restaurante, hamburgueria, pizzaria, lanchonete, delivery de comida, bar, food, rodízio, marmita",
  academia: "academia, crossfit, estúdio de treino, personal trainer, musculação, pilates, fitness presencial, box",
  automotivo: "oficina mecânica, concessionária, lava-rápido, funilaria, estética automotiva, auto center, troca de óleo, mecânico",
  beleza: "salão de beleza, barbearia, cabeleireiro, sobrancelha, manicure, maquiagem, studio de beleza, estética não médica",
  petshop: "petshop, clínica veterinária, banho e tosa, pet, agropet, hotel para pets, adestramento, ração",
  turismo: "agência de viagens, pacotes turísticos, hotel, pousada, turismo, intercâmbio, passagens, viagem",
  eventos: "buffet, casa de festas, organização de eventos, decoração, festa, aniversário, formatura, cerimonial, casamento",
  educacao: "escola, curso de idiomas, reforço escolar, pré-vestibular, curso técnico, colégio, educação presencial, inglês",
  reforma: "reforma residencial, empreiteira, pedreiro, construção, obra, pintura, marcenaria, gesso, drywall, pequenas reformas",
  moda: "loja de roupa, boutique, moda, vestuário, brechó, moda autoral, personal stylist, ateliê, semijoias",
  financas: "assessoria de investimentos, planejamento financeiro, consultoria financeira, corretora, crédito, educação financeira, previdência",
  seguros: "corretor de seguros, seguro de vida, seguro auto, plano de saúde, seguro residencial, previdência, seguro empresarial",
  saude: "psicólogo, terapeuta, nutricionista, fisioterapeuta, bem-estar, terapia, saúde mental, acupuntura, consultório",
  tecnologia: "assistência técnica, conserto de celular, informática, suporte de TI, manutenção de computador, eletrônicos, conserto de notebook",
  confeitaria: "confeitaria, bolo de aniversário, doces, brigadeiro gourmet, encomenda de bolo, padaria artesanal, festa, docinhos",
  limpeza: "empresa de limpeza, diarista, faxina, dedetização, limpeza pós-obra, conservação, terceirização, higienização de estofado",
  energiasolar: "energia solar, painel solar, placa fotovoltaica, instalação solar, economia na conta de luz, gerador de energia, fotovoltaico",
  agro: "agronegócio, insumos agrícolas, máquinas agrícolas, pecuária, fazenda, agro, sementes, defensivos, irrigação",
  logistica: "transportadora, mudança, frete, logística, entrega, carreto, armazenagem, motoboy, distribuição",
  fotografia: "fotógrafo, estúdio fotográfico, filmmaker, audiovisual, fotografia de casamento, ensaio, vídeo, foto de produto",
  generico: 'quando nenhum acima encaixa com confiança',
}
